#!/bin/bash
# ─────────────────────────────────────────────
# spawn_agent.sh
# Creates a git worktree and spawns an agent
# in its own tmux session with the correct model.
#
# Usage:
#   ./scripts/spawn_agent.sh <task_id> <agent_type> <tier> <"task description">
#
# Tiers:
#   1   = Ollama/Gemma4:e2b (local, free, 0.79s)
#         Health monitoring, log watching, immune system checks
#
#   2   = Ollama/Gemma4:e4b (local, free, 5.86s)
#         Signal agent, code hygiene, training librarian
#         Simple well-defined coding tasks
#
#   2.5 = Claude Haiku 4.5 ($1/$5 per MTok)
#         Integration-test, bounded sub-agent tasks
#         Tasks needing Anthropic reliability without Sonnet cost
#
#   3   = Claude Sonnet 4.6 ($3/$15 per MTok)
#         Quant research, backtest validation, market builder
#         Complex multi-file reasoning
#
#   4   = Claude Opus 4.6 ($5/$25 per MTok, escalation only)
#         Architecture decisions, tasks that failed Tier 3 three times
#         Genuine architectural design questions
#
# Routing reference: /brain/model-routing.md
#
# Example:
#   ./scripts/spawn_agent.sh elo-brier-001 quant-research 3 \
#     "Calculate Brier scores for ELO predictions across all resolved markets"
#
# ── SECURITY NOTE (audited 2026-04-30) ───────
# Context passed to agents is limited to:
#   - Task template (orchestrator/task_templates/<agent_type>.md)
#   - brain/priorities.md
#   - brain/model-routing.md
#   - TASK_ID (internal, generated by orchestrator or cron — never from user input)
#   - Tier and model name
#   - UTC timestamp
#
# Git history is NEVER read or interpolated into agent prompts by this script.
# No git log, git show, or git diff calls are made.
#
# Claude CLI tiers (2.5/3/4) are invoked with -p (print/one-shot mode),
# which processes a single prompt and exits — no interactive git-status
# injection occurs in this mode.
#
# All callers of this script are internal (orchestrator.py, cron jobs).
# TASK_ID originates from orchestrator-generated IDs or date strings,
# never from external or user-controlled input.
# ─────────────────────────────────────────────

set -e  # Exit on any error

# ── Arguments ──────────────────────────────
TASK_ID=$1
AGENT_TYPE=$2
TIER=${3:-3}          # Default to Sonnet if not specified
TASK_DESC=$4

# ── Validate arguments ──────────────────────
if [ -z "$TASK_ID" ] || [ -z "$AGENT_TYPE" ] || [ -z "$TASK_DESC" ]; then
    echo "ERROR: Missing required arguments"
    echo "Usage: $0 <task_id> <agent_type> <tier> <description>"
    echo ""
    echo "Tiers:"
    echo "  1   = Ollama/Gemma4:e2b (local, free, 0.79s)"
    echo "  2   = Ollama/Gemma4:e4b (local, free, 5.86s)"
    echo "  2.5 = Claude Haiku 4.5 (\$1/\$5 per MTok)"
    echo "  3   = Claude Sonnet 4.6 (\$3/\$15 per MTok)"
    echo "  4   = Claude Opus 4.6 (\$5/\$25 per MTok, escalation only)"
    echo ""
    echo "See /brain/model-routing.md for per-agent routing decisions."
    exit 1
fi

# ── Configuration ───────────────────────────
BASE_DIR="/home/parison/trading-swarm"
WORKTREES_DIR="/tmp/trading-swarm-worktrees"
TEMPLATE_FILE="$BASE_DIR/orchestrator/task_templates/$AGENT_TYPE.md"
REGISTRY_FILE="$BASE_DIR/orchestrator/agent_registry.json"
BRAIN_DIR="$BASE_DIR/brain"
SESSION_NAME="$AGENT_TYPE-$TASK_ID"
BRANCH_NAME="feat/$TASK_ID"
WORKTREE_PATH="$WORKTREES_DIR/$TASK_ID"
LOG_FILE="$BASE_DIR/logs/agent_logs/$TASK_ID.log"
PROMPT_FILE="/tmp/$TASK_ID.prompt"
CLEANUP_FILE="/tmp/$TASK_ID.cleanup.py"

# ── Select model based on tier ───────────────
case $TIER in
    1)
        MODEL_CMD="ollama run gemma4:e2b --think=false"
        MODEL_NAME="gemma4:e2b (local, Tier 1)"
        NEEDS_WORKTREE=false
        ;;
    2)
        MODEL_CMD="ollama run gemma4:e4b --think=false"
        MODEL_NAME="gemma4:e4b (local, Tier 2)"
        NEEDS_WORKTREE=false
        ;;
    2.5)
        MODEL_CMD="claude --model claude-haiku-4-5-20251001 --dangerously-skip-permissions -p"
        MODEL_NAME="claude-haiku-4-5 (Tier 2.5)"
        NEEDS_WORKTREE=true
        ;;
    3)
        MODEL_CMD="claude --model claude-sonnet-4-6 --dangerously-skip-permissions -p"
        MODEL_NAME="claude-sonnet-4-6 (Tier 3)"
        NEEDS_WORKTREE=true
        ;;
    4)
        MODEL_CMD="claude --model claude-opus-4-7 --dangerously-skip-permissions -p"
        MODEL_NAME="claude-opus-4-7 (Tier 4, escalation)"
        NEEDS_WORKTREE=true
        ;;
    *)
        echo "ERROR: Invalid tier '$TIER'"
        echo "Valid tiers: 1, 2, 2.5, 3, 4"
        echo "See /brain/model-routing.md for guidance."
        exit 1
        ;;
esac

echo "──────────────────────────────────────"
echo "Spawning agent: $SESSION_NAME"
echo "Model: $MODEL_NAME"
echo "Task: $TASK_DESC"
echo "──────────────────────────────────────"

# ── Validate template exists ─────────────────
if [ ! -f "$TEMPLATE_FILE" ]; then
    FALLBACK_TEMPLATE="$BASE_DIR/orchestrator/task_templates/$AGENT_TYPE-agent.md"
    if [ -f "$FALLBACK_TEMPLATE" ]; then
        TEMPLATE_FILE="$FALLBACK_TEMPLATE"
    else
        echo "ERROR: Template not found: $TEMPLATE_FILE"
        exit 1
    fi
fi

# ── Check session not already running ────────
if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
    echo "ERROR: Session $SESSION_NAME already exists"
    echo "Kill it first: tmux kill-session -t $SESSION_NAME"
    exit 1
fi

# ── Read template and inject task description ─
TEMPLATE=$(cat "$TEMPLATE_FILE")
FULL_PROMPT="${TEMPLATE/\{TASK_DESCRIPTION\}/$TASK_DESC}"

# ── Read current brain context ────────────────
PRIORITIES=$(cat "$BRAIN_DIR/priorities.md" 2>/dev/null || echo "No priorities set")
ROUTING=$(cat "$BRAIN_DIR/model-routing.md" 2>/dev/null || echo "No routing doc found")

# ── Build complete agent prompt ───────────────
AGENT_PROMPT="$FULL_PROMPT

## Current System Priorities
$PRIORITIES

## Model Routing Reference
$ROUTING

## Task ID
$TASK_ID

## Model Tier
Tier $TIER — $MODEL_NAME

## Started At
$(date -u +%Y-%m-%dT%H:%M:%SZ)
"

# ── Save prompt to log and temp file ─────────
mkdir -p "$(dirname $LOG_FILE)"
echo "=== Agent Prompt ===" > "$LOG_FILE"
echo "$AGENT_PROMPT" >> "$LOG_FILE"
echo "=== Agent Output ===" >> "$LOG_FILE"

# Write to temp file to avoid tmux character limit when passing prompt inline
printf '%s' "$AGENT_PROMPT" > "$PROMPT_FILE"

# Write registry cleanup script — runs inside tmux after agent exits
cat > "$CLEANUP_FILE" << 'CLEANUP_EOF'
import json, sys
registry_path = '/home/parison/trading-swarm/orchestrator/agent_registry.json'
task_id = sys.argv[1]
try:
    with open(registry_path) as f:
        registry = json.load(f)
    for t in registry['active_tasks']:
        if t['id'] == task_id:
            t['status'] = 'completed'
            break
    with open(registry_path, 'w') as f:
        json.dump(registry, f, indent=2)
    registry['active_tasks'] = [t for t in registry['active_tasks'] if t['id'] != task_id]
    with open(registry_path, 'w') as f:
        json.dump(registry, f, indent=2)
    print(f'[REGISTRY] Cleaned up task {task_id}')
except Exception as e:
    print(f'[REGISTRY] Cleanup failed: {e}')
CLEANUP_EOF

# ── Create git worktree for paid tiers ────────
if [ "$NEEDS_WORKTREE" = true ]; then
    echo "Creating git worktree: $BRANCH_NAME"
    mkdir -p "$WORKTREES_DIR"

    if [ -d "$WORKTREE_PATH" ]; then
        echo "Worktree already exists at $WORKTREE_PATH"
    else
        git -C "$BASE_DIR" worktree add "$WORKTREE_PATH" -b "$BRANCH_NAME" 2>/dev/null || \
        git -C "$BASE_DIR" worktree add "$WORKTREE_PATH" "$BRANCH_NAME"
    fi
    WORKING_DIR="$WORKTREE_PATH"
else
    # Local models work directly in base dir
    WORKING_DIR="$BASE_DIR"
fi

# ── Spawn tmux session ────────────────────────
echo "Spawning tmux session: $SESSION_NAME"

tmux new-session -d \
    -s "$SESSION_NAME" \
    -c "$WORKING_DIR" \
    -x 220 -y 50

# ── Run the agent inside the session ─────────
if [ "$NEEDS_WORKTREE" = true ]; then
    # Paid Claude models: read prompt from file to avoid tmux character limit
    tmux send-keys -t "$SESSION_NAME" \
        "$MODEL_CMD \"\$(cat $PROMPT_FILE)\" 2>&1 | tee -a $LOG_FILE; rm -f $PROMPT_FILE; python3 $CLEANUP_FILE $TASK_ID >> $LOG_FILE 2>&1; rm -f $CLEANUP_FILE" \
        Enter
else
    # Local Ollama models: read prompt from file to avoid tmux character limit
    tmux send-keys -t "$SESSION_NAME" \
        "cat $PROMPT_FILE | $MODEL_CMD 2>&1 | tee -a $LOG_FILE; rm -f $PROMPT_FILE; python3 $CLEANUP_FILE $TASK_ID >> $LOG_FILE 2>&1; rm -f $CLEANUP_FILE" \
        Enter
fi

# ── Register task in registry ─────────────────
# Write TASK_DESC to a temp file so special chars (em-dashes, newlines,
# quotes) don't break Python string interpolation inside the heredoc.
TASK_DESC_FILE="/tmp/${TASK_ID}.taskdesc"
printf '%s' "$TASK_DESC" > "$TASK_DESC_FILE"

python3 - <<EOF
import json
from datetime import datetime
from pathlib import Path

registry_file = Path("$REGISTRY_FILE")
with open(registry_file) as f:
    registry = json.load(f)

with open("$TASK_DESC_FILE") as f:
    task_desc = f.read()

registry["active_tasks"].append({
    "id": "$TASK_ID",
    "agent": "$AGENT_TYPE",
    "description": task_desc[:200],
    "branch": "$BRANCH_NAME",
    "tmux_session": "$SESSION_NAME",
    "model": "$MODEL_NAME",
    "tier": "$TIER",
    "worktree": "$WORKTREE_PATH" if "$NEEDS_WORKTREE" == "true" else None,
    "log": "$LOG_FILE",
    "started_at": datetime.utcnow().isoformat(),
    "status": "running",
    "retries": 0,
    "pr": None,
    "verified": False
})

with open(registry_file, "w") as f:
    json.dump(registry, f, indent=2)

Path("$TASK_DESC_FILE").unlink(missing_ok=True)
print("Task registered in registry")
EOF

# ── Confirm ───────────────────────────────────
echo ""
echo "✓ Agent spawned successfully"
echo "  Session:  $SESSION_NAME"
echo "  Model:    $MODEL_NAME"
echo "  Branch:   $BRANCH_NAME"
echo "  Logs:     $LOG_FILE"
echo ""
echo "Watch it:   tmux attach -t $SESSION_NAME"
echo "Detach:     Ctrl+B then D"
echo "Kill it:    tmux kill-session -t $SESSION_NAME"
echo ""
echo "Routing decisions: /brain/model-routing.md"
